-- ====================================================================
-- UPDATE: Profil uživatele, statistiky, přátelé a nahrávání avatarů
-- ====================================================================

-- a) Přidání sloupců do tabulky uzivatele pro avatar a herní statistiky
ALTER TABLE public.uzivatele 
ADD COLUMN IF NOT EXISTS avatar_url text,
ADD COLUMN IF NOT EXISTS games_played int DEFAULT 0,
ADD COLUMN IF NOT EXISTS games_won int DEFAULT 0,
ADD COLUMN IF NOT EXISTS skulls_drawn int DEFAULT 0;

-- b) Vytvoření tabulky friendships se systémem žádostí o přátelství
CREATE TABLE IF NOT EXISTS public.friendships (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id bigint REFERENCES public.uzivatele(id) ON DELETE CASCADE,
    addressee_id bigint REFERENCES public.uzivatele(id) ON DELETE CASCADE,
    status text DEFAULT 'pending',
    created_at timestamptz DEFAULT now(),
    CONSTRAINT unique_friendship UNIQUE (requester_id, addressee_id)
);

-- Povolení Realtime pro friendships
DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.friendships;
    EXCEPTION WHEN duplicate_object THEN
        NULL;
    END;
END
$$;

-- RLS politiky pro friendships (plný přístup pro aplikaci)
ALTER TABLE public.friendships ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public friendships policy" ON public.friendships;
CREATE POLICY "Public friendships policy" ON public.friendships FOR ALL USING (true) WITH CHECK (true);

-- c) Vytvoření veřejného Storage bucketu avatars a bezpečnostních politik
INSERT INTO storage.buckets (id, name, public) 
VALUES ('avatars', 'avatars', true) 
ON CONFLICT (id) DO UPDATE SET public = true;

-- Politiky pro storage.objects (čtení, nahrávání, úpravy i mazání avatarů)
DROP POLICY IF EXISTS "Public Read Avatars" ON storage.objects;
CREATE POLICY "Public Read Avatars" ON storage.objects FOR SELECT USING (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Public Insert Avatars" ON storage.objects;
CREATE POLICY "Public Insert Avatars" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Public Update Avatars" ON storage.objects;
CREATE POLICY "Public Update Avatars" ON storage.objects FOR UPDATE USING (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Public Delete Avatars" ON storage.objects;
CREATE POLICY "Public Delete Avatars" ON storage.objects FOR DELETE USING (bucket_id = 'avatars');
