-- =========================================================
-- Alchymista Hra - Supabase Inicializační SQL Skript
-- Tento skript spusťte v Supabase: Dashboard -> SQL Editor
-- =========================================================

-- =========================================================
-- DŮLEŽITÉ INSTRUKCE PRO MIGRACI ZE STARŠÍCH VERZÍ:
--
-- 1) Pokud tabulky již existují a chcete je kompletně zresetovat na čisté relační schéma:
--    DROP TABLE IF EXISTS public.room_players CASCADE;
--    DROP TABLE IF EXISTS public.rooms CASCADE;
--    DROP TABLE IF EXISTS public.uzivatele CASCADE;
--    DROP TABLE IF EXISTS public.skore CASCADE;
--
-- 2) Pokud chcete zachovat data a provést migraci za běhu:
--    -- Povolení NULL hesel pro hosty:
--    ALTER TABLE public.uzivatele ALTER COLUMN heslo DROP NOT NULL;
--    -- Odstranění starých denormalizovaných sloupců:
--    ALTER TABLE public.rooms DROP COLUMN IF EXISTS host_name;
--    ALTER TABLE public.room_players DROP COLUMN IF EXISTS prezdivka;
--    -- Přidání cizích klíčů a oprava typů (pokud byly text):
--    ALTER TABLE public.rooms ALTER COLUMN host_id TYPE BIGINT USING host_id::bigint;
--    ALTER TABLE public.rooms ADD CONSTRAINT fk_rooms_host FOREIGN KEY (host_id) REFERENCES public.uzivatele(id) ON DELETE CASCADE;
--    ALTER TABLE public.room_players ALTER COLUMN player_id TYPE BIGINT USING player_id::bigint;
--    ALTER TABLE public.room_players ADD CONSTRAINT fk_room_players_player FOREIGN KEY (player_id) REFERENCES public.uzivatele(id) ON DELETE CASCADE;
-- =========================================================

-- 1. Tabulka UŽIVATELÉ (uzivatele)
CREATE TABLE IF NOT EXISTS public.uzivatele (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prezdivka TEXT NOT NULL UNIQUE,
    email TEXT UNIQUE,
    heslo TEXT DEFAULT NULL, -- Pro hosty může být heslo NULL
    role TEXT DEFAULT 'hrac', -- 'hrac', 'guest', 'admin'
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabulka MÍSTNOSTI / LABORATOŘE (rooms)
CREATE TABLE IF NOT EXISTS public.rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_code TEXT NOT NULL UNIQUE,
    host_id BIGINT NOT NULL REFERENCES public.uzivatele(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'waiting',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabulka HRÁČI V MÍSTNOSTI (room_players) - pro Supabase Realtime
CREATE TABLE IF NOT EXISTS public.room_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_code TEXT NOT NULL REFERENCES public.rooms(room_code) ON DELETE CASCADE,
    player_id BIGINT NOT NULL REFERENCES public.uzivatele(id) ON DELETE CASCADE,
    is_guest BOOLEAN DEFAULT FALSE,
    is_host BOOLEAN DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending' | 'approved'
    joined_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_player_in_room UNIQUE (room_code, player_id)
);

-- Povolení Row Level Security (RLS)
ALTER TABLE public.uzivatele ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_players ENABLE ROW LEVEL SECURITY;

-- Politiky pro přístup z klientské aplikace (anon key)
-- Uživatelé: čtení a zápis
DROP POLICY IF EXISTS "Public select uzivatele" ON public.uzivatele;
CREATE POLICY "Public select uzivatele" ON public.uzivatele FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public insert uzivatele" ON public.uzivatele;
CREATE POLICY "Public insert uzivatele" ON public.uzivatele FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public update uzivatele" ON public.uzivatele;
CREATE POLICY "Public update uzivatele" ON public.uzivatele FOR UPDATE USING (true);

-- Místnosti: plný přístup pro hráče (čtení, vytváření, mazání při opuštění)
DROP POLICY IF EXISTS "Public rooms policy" ON public.rooms;
CREATE POLICY "Public rooms policy" ON public.rooms FOR ALL USING (true) WITH CHECK (true);

-- Hráči v místnosti: plný přístup pro hráče (čtení, připojení, aktualizace statusu, odchod)
DROP POLICY IF EXISTS "Public room_players policy" ON public.room_players;
CREATE POLICY "Public room_players policy" ON public.room_players FOR ALL USING (true) WITH CHECK (true);

-- =========================================================
-- Zapnutí Supabase Realtime pro tabulky
-- =========================================================
DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.rooms;
    EXCEPTION WHEN duplicate_object THEN
        NULL;
    END;

    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.room_players;
    EXCEPTION WHEN duplicate_object THEN
        NULL;
    END;
END
$$;