-- =========================================================
-- Alchymista Hra - Supabase Inicializační SQL Skript
-- Tento skript spusťte v Supabase: Dashboard -> SQL Editor
-- =========================================================

-- 1. Tabulka UŽIVATELÉ (uzivatele)
CREATE TABLE IF NOT EXISTS public.uzivatele (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prezdivka TEXT NOT NULL UNIQUE,
    email TEXT UNIQUE,
    heslo TEXT NOT NULL,
    role TEXT DEFAULT 'hrac',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabulka MÍSTNOSTI / LABORATOŘE (rooms)
CREATE TABLE IF NOT EXISTS public.rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_code TEXT NOT NULL UNIQUE,
    host_id TEXT NOT NULL,
    host_name TEXT NOT NULL,
    status TEXT DEFAULT 'waiting',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabulka HRÁČI V MÍSTNOSTI (room_players) - pro Supabase Realtime
CREATE TABLE IF NOT EXISTS public.room_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_code TEXT NOT NULL REFERENCES public.rooms(room_code) ON DELETE CASCADE,
    player_id TEXT NOT NULL,
    prezdivka TEXT NOT NULL,
    is_guest BOOLEAN DEFAULT FALSE,
    is_host BOOLEAN DEFAULT FALSE,
    joined_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_player_in_room UNIQUE (room_code, player_id)
);

-- 4. Tabulka SKÓRE / SÍŇ SLÁVY (skore)
CREATE TABLE IF NOT EXISTS public.skore (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prezdivka TEXT NOT NULL,
    body INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Povolení Row Level Security (RLS)
ALTER TABLE public.uzivatele ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skore ENABLE ROW LEVEL SECURITY;

-- Politiky pro přístup z klientské aplikace (anon key)
-- Uživatelé: čtení a zápis
DROP POLICY IF EXISTS "Public select uzivatele" ON public.uzivatele;
CREATE POLICY "Public select uzivatele" ON public.uzivatele FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public insert uzivatele" ON public.uzivatele;
CREATE POLICY "Public insert uzivatele" ON public.uzivatele FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public update uzivatele" ON public.uzivatele;
CREATE POLICY "Public update uzivatele" ON public.uzivatele FOR UPDATE USING (true);

-- Místnosti: plný přístup pro hráče
DROP POLICY IF EXISTS "Public rooms policy" ON public.rooms;
CREATE POLICY "Public rooms policy" ON public.rooms FOR ALL USING (true) WITH CHECK (true);

-- Hráči v místnosti: plný přístup pro hráče (čtení, připojení, odchod)
DROP POLICY IF EXISTS "Public room_players policy" ON public.room_players;
CREATE POLICY "Public room_players policy" ON public.room_players FOR ALL USING (true) WITH CHECK (true);

-- Skóre: čtení a vkládání bodů
DROP POLICY IF EXISTS "Public skore policy" ON public.skore;
CREATE POLICY "Public skore policy" ON public.skore FOR ALL USING (true) WITH CHECK (true);

-- =========================================================
-- Zapnutí Supabase Realtime pro tabulky
-- =========================================================
DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.rooms;
    EXCEPTION WHEN duplicate_object THEN
        NULL;
    END;

    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.room_players;
    EXCEPTION WHEN duplicate_object THEN
        NULL;
    END;

    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.skore;
    EXCEPTION WHEN duplicate_object THEN
        NULL;
    END;
END
$$;

-- Volitelné: Ukázkové záznamy do Síně slávy pro otestování žebříčku
INSERT INTO public.skore (prezdivka, body) VALUES
    ('Paracelsus', 450),
    ('Edward_Kelly', 320),
    ('Nicolas_Flamel', 580)
ON CONFLICT DO NOTHING;
